package vb.queue.com.queueforverb.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import vb.queue.com.adverforverb.entry.VideoInfo;
import vb.queue.com.adverforverb.entry.OrderInfo;
import vb.queue.com.adverforverb.entry.NoticeInfo;
import vb.queue.com.adverforverb.entry.SettingInfo;
import vb.queue.com.adverforverb.entry.RoomsInfo;

import vb.queue.com.queueforverb.greendao.VideoInfoDao;
import vb.queue.com.queueforverb.greendao.OrderInfoDao;
import vb.queue.com.queueforverb.greendao.NoticeInfoDao;
import vb.queue.com.queueforverb.greendao.SettingInfoDao;
import vb.queue.com.queueforverb.greendao.RoomsInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoInfoDaoConfig;
    private final DaoConfig orderInfoDaoConfig;
    private final DaoConfig noticeInfoDaoConfig;
    private final DaoConfig settingInfoDaoConfig;
    private final DaoConfig roomsInfoDaoConfig;

    private final VideoInfoDao videoInfoDao;
    private final OrderInfoDao orderInfoDao;
    private final NoticeInfoDao noticeInfoDao;
    private final SettingInfoDao settingInfoDao;
    private final RoomsInfoDao roomsInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoInfoDaoConfig = daoConfigMap.get(VideoInfoDao.class).clone();
        videoInfoDaoConfig.initIdentityScope(type);

        orderInfoDaoConfig = daoConfigMap.get(OrderInfoDao.class).clone();
        orderInfoDaoConfig.initIdentityScope(type);

        noticeInfoDaoConfig = daoConfigMap.get(NoticeInfoDao.class).clone();
        noticeInfoDaoConfig.initIdentityScope(type);

        settingInfoDaoConfig = daoConfigMap.get(SettingInfoDao.class).clone();
        settingInfoDaoConfig.initIdentityScope(type);

        roomsInfoDaoConfig = daoConfigMap.get(RoomsInfoDao.class).clone();
        roomsInfoDaoConfig.initIdentityScope(type);

        videoInfoDao = new VideoInfoDao(videoInfoDaoConfig, this);
        orderInfoDao = new OrderInfoDao(orderInfoDaoConfig, this);
        noticeInfoDao = new NoticeInfoDao(noticeInfoDaoConfig, this);
        settingInfoDao = new SettingInfoDao(settingInfoDaoConfig, this);
        roomsInfoDao = new RoomsInfoDao(roomsInfoDaoConfig, this);

        registerDao(VideoInfo.class, videoInfoDao);
        registerDao(OrderInfo.class, orderInfoDao);
        registerDao(NoticeInfo.class, noticeInfoDao);
        registerDao(SettingInfo.class, settingInfoDao);
        registerDao(RoomsInfo.class, roomsInfoDao);
    }
    
    public void clear() {
        videoInfoDaoConfig.clearIdentityScope();
        orderInfoDaoConfig.clearIdentityScope();
        noticeInfoDaoConfig.clearIdentityScope();
        settingInfoDaoConfig.clearIdentityScope();
        roomsInfoDaoConfig.clearIdentityScope();
    }

    public VideoInfoDao getVideoInfoDao() {
        return videoInfoDao;
    }

    public OrderInfoDao getOrderInfoDao() {
        return orderInfoDao;
    }

    public NoticeInfoDao getNoticeInfoDao() {
        return noticeInfoDao;
    }

    public SettingInfoDao getSettingInfoDao() {
        return settingInfoDao;
    }

    public RoomsInfoDao getRoomsInfoDao() {
        return roomsInfoDao;
    }

}
